version: '3.8'

services:
  fhoss-mysql:
    image: mysql:8.0
    container_name: fhoss-mysql
    ports: [ "3306:3306" ]
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: hss_db
      MYSQL_USER: hss
      MYSQL_PASSWORD: hss
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:                  
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      ims-net:
        aliases: [ "fhoss-mysql" ]

  fhoss:
    image: gradiant/fhoss:develop
    volumes:
      - ./fhoss-config/DiameterPeerHSS.xml:/opt/OpenIMSCore/FHoSS/config/DiameterPeerHSS.xml
    container_name: fhoss
    ports: [ "8080:8080", "3868:3868" ] # HSS (web + diameter)
    depends_on: [ fhoss-mysql ]
    environment:
      IMS_DOMAIN: ims.sipify
      MYSQL_HOST: fhoss-mysql
      MYSQL_IP: fhoss-mysql
      FHOSS_IP: fhoss
      DNS_IP: 127.0.0.11
      MYSQL_USER: hss
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: hss
      MYSQL_DATABASE: hss_db
    networks:
      ims-net:
        aliases: [ "hss.ims.sipify", "fhoss" ]

  # ------- P-CSCF -------
  kamailio-pcscf:
    image: local/kamailio-ims:6.0.3
    container_name: kamailio-pcscf
    volumes:
      - ./kamailio/pcscf:/etc/kamailio:ro
    command: >
      bash -lc 'kamailio -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -DD -E'
    ports:
      - "5080:4060/tcp"
      - "5080:4060/udp"
      - "3871:3871/tcp" # Diameter acceptor for P-CSCF, if you configured it
    depends_on: [ fhoss ]
    networks:
      ims-net:
        aliases: [ "pcscf.ims.sipify" ]

  # ------- I-CSCF -------
  kamailio-icscf:
    image: local/kamailio-ims:6.0.3
    container_name: kamailio-icscf
    volumes:
      - ./kamailio/icscf:/etc/kamailio:ro
    command: >
      bash -lc 'kamailio -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -DD -E'
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "3869:3869/tcp" # Diameter acceptor for I-CSCF
    networks:
      ims-net:
        aliases: [ "icscf.ims.sipify" ]
    depends_on: [ fhoss ]

  # ------- S-CSCF -------
  kamailio-scscf:
    image: local/kamailio-ims:6.0.3
    container_name: kamailio-scscf
    volumes:
      - ./kamailio/scscf:/etc/kamailio:ro
    command: >
      bash -lc 'kamailio -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -DD -E'
    ports:
      - "6060:6060/tcp"
      - "6060:6060/udp"
      - "3870:3870/tcp" # Diameter acceptor for S-CSCF
    networks:
      ims-net:
        aliases: [ "scscf.ims.sipify" ]
    depends_on: [ fhoss ]

volumes:
  mysql_data:


networks:
  ims-net:
    driver: bridge
