version: '3.8'

services:
  fhoss-mysql:
    image: mysql:8.0
    container_name: fhoss-mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fhoss_db
      MYSQL_USER: fhoss
      MYSQL_PASSWORD: fhosspass
    ports: ["3306:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [ims-net]

  fhoss:
    image: gradiant/fhoss:develop
    container_name: fhoss
    environment:
      MYSQL_IP: fhoss-mysql
      FHOSS_IP: fhoss
      MYSQL_USER: fhoss
      MYSQL_PASSWORD: fhosspass
      MYSQL_DATABASE: fhoss_db
    ports:
      - "8080:8080"
      - "3868:3868"
    depends_on: [fhoss-mysql]
    networks: [ims-net]

  # P-CSCF
  kamailio-pcscf:
    image: local/kamailio-ims:6.0.3
    container_name: kamailio-pcscf
    network_mode: "host"
    volumes:
      - ./kamailio/pcscf:/etc/kamailio:ro
    command: kamailio -f /etc/kamailio/kamailio.cfg -DD -E
    depends_on:
      - fhoss

  # I-CSCF
  kamailio-icscf:
    image: local/kamailio-ims:6.0.3
    container_name: kamailio-icscf
    network_mode: "host"
    volumes:
      - ./kamailio/icscf:/etc/kamailio:ro
    command: kamailio -f /etc/kamailio/kamailio.cfg -DD -E
    depends_on:
      - fhoss

  # S-CSCF
  kamailio-scscf:
    image: local/kamailio-ims:6.0.3
    container_name: kamailio-scscf
    network_mode: "host"
    volumes:
      - ./kamailio/scscf:/etc/kamailio:ro
    command: kamailio -f /etc/kamailio/kamailio.cfg -DD -E
    depends_on:
      - fhoss

volumes:
  mysql_data:

networks:
  ims-net:
    driver: bridge
